packages:
  - "."
  - "examples/*"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*vitest*"
  - "typescript"
  - "*rimraf*"
  - "*cross-env*"

overrides:
  vite: "7.3.3"

minimumReleaseAgeExclude:
  - "*functype*"
  - "ts-builds"
  - fastmcp@4.17.1

allowBuilds:
  esbuild: true
  tldjs: true
